name: Template to build and Push to ACR 

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  IMAGE_NAME: kubeconacr.azurecr.io/kubecon-rockets:latest
  K8S_NAMESPACE: default
  K8S_DEPLOYMENT: kubecon-rockets
  AZ_RESOURCE_GROUP: kubeconResourceGroup
  AZ_CLUSTER_NAME: kubeconAKSCluster
  AZURE_CREDENTIALS : ${{ secrets.AZURE_CREDENTIALS_ROCKETS }}
    
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_MT }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
       - name: Login to ACR
        run: |
          az acr login --name <acrName> --verbose

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: <user/app:latest>
          

          
          tags: kubeconacr.azurecr.io/kubecon-rockets:latest
