name: Parse issue form
on:
  issues:
    types:
      - opened     
      - reopened

jobs:
  extract_issue_data:
    name: Extract issue data
    if: contains(github.event.issue.labels.*.name, 'a label')

    runs-on: ubuntu-latest

    outputs:
      runner_payload: ${{ steps.issue_payload.outputs.payload }}

    steps:
      - name: Get temporary token for creating deployment
        id: temp_token
        uses: peter-murray/workflow-application-token-action@v1.0.3
        with:
          application_id: ${{ secrets.ISSUE_PARSER_APP_ID }}
          application_private_key: ${{ secrets.ISSUE_PARSER_APP_KEY }}

      - name: Extract Issue Payload Data
        id: issue_payload
        uses: peter-murray/issue-forms-body-parser@v1.1.0
        with:
          separator: '###'
          issue_id: ${{ github.event.issue.number }}
          label_marker_start: ' '
          label_marker_end: ':' 
      
      - name: Show parsed data JSON
        run: |
          echo "${{ steps.issue_payload.outputs.payload }}"

